app = "ai-coworker-for-businesses"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[http_service]
  auto_start_machines = true
  auto_stop_machines = "stop"
  force_https = true
  internal_port = 8_000
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  destination = "/app/data"
  source = "ai_coworker_data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
  memory_mb = 1_024

